---
title: "endbericht_tests"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(REdaS)
library(rela)
library(psych)
library(ggplot2)

dataset <- read.table("data/dataset.csv", header=TRUE, sep=";")
attach(dataset)

# Auswahl von Spalte 2 bis 48 (-> nur die Likert Skalen)
spalte2bis48 <- dataset[,2:48]


# Antworten einer Frage umkehren (da negative Frage)
cols = c("C7Unterstuetzen", "C14InterKulturen", "F26Nafri")

dataset[ ,cols] = 5 - dataset[ ,cols]

```



----------------------------------------------------------------------------------------------------------------------------------------------
## Geschlecht

Männer-Frauen Anteil der Befragten. 

```{r }
lblsS <- c("Männlich","Weiblich")
pctS <- round(table(I_sex)/sum(table(I_sex))*100)
lblsS <- paste(lblsS, pctS) # add percents to labels
lblsS <- paste(lblsS,"%",sep="") # ad % to labels
pie(table(I_sex),labels = lblsS, cex=1,cex.main=1.5, col=c("blue","red"), main = "Verteilung Geschlecht Fragebogen")
```

Statistik Männer Frauen an der WU 2015/2016
Männer;11.558	Frauen: 10.284
```{r }
statistikSex <- c(11558,10284)
lblsS <- c("Männlich","Weiblich")
pctS <- round(statistikSex/sum(statistikSex)*100)
lblsS <- paste(lblsS, pctS) # add percents to labels
lblsS <- paste(lblsS,"%",sep="") # ad % to labels
pie(statistikSex,labels = lblsS, cex=1,cex.main=1.5, col=c("blue","red"), main = "Statistik WU Geschlecht")
```
Vergleich chi-square Geschelcht
63Männer, 37Frauen in Strichprobe - Tatsächliche verteilung 53%-47%(M-W)
```{r}
chisq.test(x = c(63,37),p = c(0.53,0.47))

```
< 0,05 das heist die Stichprobe ist nicht repräsentativ für die tatsächliche Verteilung aber knapp dran
----------------------------------------------------------------------------------------------------------------------------------------------

##Alter

Analysen zum Alter der Befragten 

Boxplot Alter:
```{r}
boxplot(I_age, main="Altersverteilung")
```
```{r}
par(mar = c(4,4,4,4) + 0.1)
barplot(table(factor(I_age, levels = 17:43)), main="Altersverteilung",cex.axis = 0.8 ,cex.names = 0.5)
```
Test auf Normalvertielung
```{r}
shapiro.test(table(I_age))
```
Alter ist nicht Normalverteilt (< 0,05)
----------------------------------------------------------------------------------------------------------------------------------------------

##Herkunft

```{r}
barplot(summary(I_country), main="Herkunftsland",
   ylab="Anzahl", cex.names=0.9, las=2)
```
Stichprobe:  80      = Österreich  20    = Ausland => 80/20
Tatsächlich: 16.086  = Österreich  5.756 = Ausland => 73,65/26,35
```{r}
chisq.test(x = c(80,20),p = c(0.74,0.26))
```

Die Stichprobe nach Herkunft ist repräsentativ
--------------------------------------------------------------------------------------------------------------------------------------------


##Hypothese 1 - Variablenauswertung

Je mehr Informationen aus Qualitätszeitungen bezogen werden, desto geringer ist die Anfälligkeit für Vorurteile gegenüber Migranten. 

##UV Quelle von Informationen

Summenscore Qualitätszeitungen (1 Täglich, ..., 4 Nie - muss umgedreht werden für Summenscore)
```{r}
qualMedien <- data.frame(A4Standard,A5Presse,A6Kurier,A7WienerZ)
qualMedienRev = 5 - qualMedien #umdrehen 1->4, 4->1
qualMedienRev$score = qualMedienRev$A4Standard+qualMedienRev$A5Presse+qualMedienRev$A6Kurier+qualMedienRev$A7WienerZ
qualMedienRev$score #summenscores

```

Summenscores umformen wie oft qualitäts Medien konsumiert werden (4-6 = 1 kaum, 7-9 = 2 regelmäßig, 10-16 = 3 oft)
```{r}


for (i in 1:100) {
  if (qualMedienRev$score[i] <= 6){
    qualMedienRev$score2[i] <- 1
  } else if (qualMedienRev$score[i] <= 9){
    qualMedienRev$score2[i] <- 2
  } else
    qualMedienRev$score2[i] <- 3
    
}
qualMedienRev$score2
```
Plot zu den neuen Gruppen:
```{r}
category <- c("kaum", "regelmäßig","oft")
barplot(table(qualMedienRev$score2), names.arg = category , ylab = "Häufigkeit", main = "Konsum Qualitätsmedien")
```

##AV Anfälligkeit für Vorurteile gegenüber Migranten

4 Stufige Likert-Skala (trifft sehr zu, trifft eher zu, trifft eher nicht zu, trifft gar nicht zu)

Bartlett Test auf Sphärizität, sehr klein können weiter machen 
```{r}

blockB <- dataset[,c(14:19)]
bart_spher(blockB)
```

Kaiser-Meyer-Olkin (KMO), alles > 0,8 sehr gut
```{r}

print(KMOS(blockB), sort = TRUE)
``` 

blockB erstellen (FragebatterieB)
Screeplot anzeigen für Anzahl der Komponenten => 1

```{r}

VSS.scree(blockB)
```

PCA durchführen
```{r}
pca.blockB <- principal(blockB, nfactors = 1)
pca.blockB

```

PCA Scores
```{r}
blockB.scores <- data.frame(pca.blockB$scores)
names(blockB.scores) <- c("AnfVorMig")
blockB.scores <- round((blockB.scores),4)
(head(blockB.scores))
```

Shapirotest Normalverteilung und density Plot
```{r}

shapiro.test(blockB.scores$AnfVorMig)

dH1 <- density(blockB.scores$AnfVorMig) # returns the density data
plot(dH1, main = "FrageblockB - Dichteverteilung")
```
## Hypothese 1 - Auswertung

Boxplot
```{r}
boxplot(blockB.scores$AnfVorMig ~ qualMedienRev$score2)
```
Kruskal-Wallis-Test
```{r}
kruskal.test(blockB.scores$AnfVorMig ~ qualMedienRev$score2)
```

H0 wird beibehalten, es besteht kein signifikanter Zusammenhang zwischen Qualitätsmedien und Anfälligkeit für Vorurteile.

---------------------------------------------------------------------------------------------------------------------------------------------


  

